### ISSUE TITLE
Arcade drive not working as intended

### ISSUE THREAD

**Issue by Felig2013** [FRCTeam4230/MainBot-Code-2019#14]
Arcade drive should use the X axis to determine the turning of the robot, and the Y-axis to set the forward or backward speed.
Intead it is seting the speed of both motors using the values of y for one motor and x for the other 

More info
https://wpilib.screenstepslive.com/s/currentCS/m/java/l/914148-driving-a-robot-using-differential-drive

**Comment by hahn2219** [comment]
fixed?
